### ISSUE TITLE
Error: '%<=%' is defunct. Use '%<-%' instead.

### ISSUE THREAD

**Issue by d7i1** [HenrikBengtsson/aroma.affymetrix#28]
**I'm making a comeback to aroma.affymetrix after several years' absence.
I reused one of my formerly-working scripts, but it fails.
FWIW, it seems to fail based on a deprecation of a to-me unfamiliar operator %<=% 
Output:**
> **source("Analyse.R")**
....libraries loading....
20170322 21:52:59|Background correcting data set...
20170322 21:52:59| Background correcting data set...
20170322 21:53:00|  Number of arrays: 24
20170322 21:53:00|  Array #1 ('GSM843555_JC-110') of 24...
20170322 21:53:00|   Identifying cells to be updated...
20170322 21:53:10|    Number of cells: 3095094
     int [1:3095094] 13 15 17 20 24 28 29 33 34 35 ...
20170322 21:53:10|   Identifying cells to be updated...done
**Error: '%<=%' is defunct.
Use '%<-%' instead.
See help("Defunct")**
20170322 21:53:10|  Array #1 ('GSM843555_JC-110') of 24...done
20170322 21:53:10| Background correcting data set...done
20170322 21:53:10|Background correcting data set...done
**script terminates here.**

> **SessionInfo()**
R version 3.2.3 (2015-12-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04 LTS

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_GB.UTF-8        LC_COLLATE=en_GB.UTF-8    
 [5] LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8   
 [7] LC_PAPER=en_GB.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] aroma.light_3.0.0      aroma.affymetrix_3.0.0 affxparser_1.42.0     
[4] aroma.core_3.0.0       R.devices_2.15.1       R.filesets_2.11.0     
[7] R.utils_2.5.0          R.oo_1.21.0            R.methodsS3_1.7.1     

loaded via a namespace (and not attached):
 [1] DNAcopy_1.44.0        XVector_0.10.0        splines_3.2.3        
 [4] IRanges_2.4.8         BiocGenerics_0.16.1   zlibbioc_1.16.0      
 [7] aroma.apd_0.6.0       R.cache_0.12.0        globals_0.9.0        
[10] tools_3.2.3           parallel_3.2.3        Biobase_2.30.0       
[13] R.huge_0.9.0          gcrma_2.42.0          affy_1.48.0          
[16] PSCBS_0.62.0          matrixStats_0.51.0    digest_0.6.12        
[19] preprocessCore_1.32.0 affyio_1.40.0         R.rsp_0.40.0         
[22] S4Vectors_0.8.11      base64enc_0.1-3       codetools_0.2-15     
[25] BiocInstaller_1.20.3  Biostrings_2.38.4     stats4_3.2.3         
[28] future_1.4.0          listenv_0.6.0        

> q()

 **I downloaded the aroma.affymetrix 3.0.0 source package.  unzipped it and grepped for instances of %<=%**
$ **grep "%<=%" `find . -name "*.R"`**
./aroma.affymetrix/R/LimmaBackgroundCorrection.R:    res[[kk]] %<=% {
./aroma.affymetrix/R/LimmaBackgroundCorrection.R:    } ## %<=%
./aroma.affymetrix/R/AllelicCrosstalkCalibration.R:    res[[kk]] %<=% {
./aroma.affymetrix/R/AllelicCrosstalkCalibration.R:    } ## %<=%
./aroma.affymetrix/R/AbstractProbeSequenceNormalization.R:    res[[kk]] %<=% {
./aroma.affymetrix/R/AbstractProbeSequenceNormalization.R:    } ## %<=%
./aroma.affymetrix/R/OpticalBackgroundCorrection.R:    res[[ii]] %<=% {
./aroma.affymetrix/R/OpticalBackgroundCorrection.R:    } ## %<=%
./aroma.affymetrix/R/MatNormalization.R:    res[[ii]] %<=% {
./aroma.affymetrix/R/MatNormalization.R:    } ## %<=%
./aroma.affymetrix/R/UnitModel.fitCnProbes.R:    res[[kk]] %<=% {
./aroma.affymetrix/R/UnitModel.fitCnProbes.R:    } # %<=%
./aroma.affymetrix/R/FragmentLengthNormalization.R:    res[[kk]] %<=% {
./aroma.affymetrix/R/FragmentLengthNormalization.R:    } ## %<=%
./aroma.affymetrix/R/AffymetrixCelSet.NORM.R:    dataFiles[[kk]] %<=% {
./aroma.affymetrix/R/AffymetrixCelSet.convertToUnique.R:      res[[kk]] %<=% {
./aroma.affymetrix/R/AffymetrixCelSet.convertToUnique.R:      } ## %<=%
./aroma.affymetrix/R/RmaBackgroundCorrection.R:    res[[ii]] %<=% {
./aroma.affymetrix/R/RmaBackgroundCorrection.R:    } ## %<=%
./aroma.affymetrix/R/GcRmaBackgroundCorrection.R:    dataFiles[[ii]] %<=% {
./aroma.affymetrix/R/GcRmaBackgroundCorrection.R:    } ## %<=%

**Hope this helps**

**Comment by HenrikBengtsson** [comment]
Oh my ..., I've been running my 48-hour real-world redundancy tests on the _develop_ versions of aroma.core / aroma.affymetrix so I missed this.  Wow.  Thanks for reporting.  (This issue was introduced by the release of future 1.4.0 on March 13).

I'll try to submit updates to CRAN that fixes this asap.  In the meanwhile, you can use develop version by installing them as:
```r
source('http://callr.org/install#HenrikBengtsson/aroma.core@develop,HenrikBengtsson/aroma.affymetrix@develop')
```
Let me know if that solves it for you.

**Comment by d7i1** [comment]
Hi,
That gets me a long way forward, but the process still fails with NA, NaN, or Inf?
(with verbose threshold -8)

```
... lots of output ...

20170323 14:12:40|                        Array #23 ('GSM843577_CL-3') of 24...
20170323 14:12:40|                         Retrieving PM and MM affinities...
20170323 14:12:41|                          PM affinities:
                           num [1:3095094] -0.585 -1.687 -1.664 -0.569 1.626 ...
20170323 14:12:41|                          MM affinities:
                           num(0) 
20170323 14:12:41|                         Retrieving PM and MM affinities...done
20170323 14:12:41|                         Retrieving PM and MM signals...
20170323 14:12:45|                          PM signals:
                           num [1:3095094] 62 83 30 72 64 186 67 69 217 64 ...
20170323 14:12:48|                          MM signals:
                           num(0) 
20170323 14:12:48|                         Retrieving PM and MM signals...done
20170323 14:12:48|                         Full GCRMA model background adjustment...
20170323 14:12:48|                          Number of PMs: 3095094
20170323 14:12:48|                          Number of MMs: 0
20170323 14:12:48|                         Full GCRMA model background adjustment...done
20170323 14:12:48|                         Array #24 ('GSM843578_CL-2') of 24...
20170323 14:12:48|                          Retrieving PM and MM affinities...
20170323 14:12:49|                           PM affinities:
                            num [1:3095094] -0.585 -1.687 -1.664 -0.569 1.626 ...
20170323 14:12:49|                           MM affinities:
                            num(0) 
20170323 14:12:49|                          Retrieving PM and MM affinities...done
20170323 14:12:49|                          Retrieving PM and MM signals...
20170323 14:12:53|                           PM signals:
                            num [1:3095094] 94 86 28 79 38 87 69 59 137 89 ...
20170323 14:12:56|                           MM signals:
                            num(0) 
20170323 14:12:56|                          Retrieving PM and MM signals...done
20170323 14:12:56|                          Full GCRMA model background adjustment...
20170323 14:12:56|                           Number of PMs: 3095094
20170323 14:12:56|                           Number of MMs: 0
20170323 14:12:56|                          Full GCRMA model background adjustment...done
20170323 14:12:56|                         Array #24 ('GSM843578_CL-2') of 24...done
Error: 'from' cannot be NA, NaN or infinite
20170323 14:12:56|                        Array #23 ('GSM843577_CL-3') of 24...done
20170323 14:12:56|                       Array #22 ('GSM843576_CL-6') of 24...done
20170323 14:12:56|                      Array #21 ('GSM843575_CL-5') of 24...done
20170323 14:12:56|                     Array #20 ('GSM843574_CL-4') of 24...done
20170323 14:12:56|                    Array #19 ('GSM843573_CL-1') of 24...done
20170323 14:12:56|                   Array #18 ('GSM843572_CN43') of 24...done
20170323 14:12:56|                  Array #17 ('GSM843571_CN42') of 24...done
20170323 14:12:56|                 Array #16 ('GSM843570_CN40') of 24...done
20170323 14:12:56|                Array #15 ('GSM843569_CN4') of 24...done
20170323 14:12:56|               Array #14 ('GSM843568_CN37') of 24...done
20170323 14:12:56|              Array #13 ('GSM843567_CN36') of 24...done
20170323 14:12:56|             Array #12 ('GSM843566_CN35') of 24...done
20170323 14:12:56|            Array #11 ('GSM843565_CN30') of 24...done
20170323 14:12:56|           Array #10 ('GSM843564_CN27') of 24...done
20170323 14:12:56|          Array #9 ('GSM843563_C14') of 24...done
20170323 14:12:56|         Array #8 ('GSM843562_C64') of 24...done
20170323 14:12:56|        Array #7 ('GSM843561_C58') of 24...done
20170323 14:12:56|       Array #6 ('GSM843560_JC-98') of 24...done
20170323 14:12:56|      Array #5 ('GSM843559_JC-103') of 24...done
20170323 14:12:56|     Array #4 ('GSM843558_C40') of 24...done
20170323 14:12:56|    Array #3 ('GSM843557_C59') of 24...done
20170323 14:12:56|   Array #2 ('GSM843556_JC-99') of 24...done
20170323 14:12:56|  Array #1 ('GSM843555_JC-110') of 24...done
20170323 14:12:56| Adjusting 24 arrays...done
20170323 14:12:56|Background correcting data set...done
Execution halted

```

**Comment by HenrikBengtsson** [comment]
What is your full script up to the point of error?

**Comment by HenrikBengtsson** [comment]
And what does `traceback()` say immediately after you get that error?

**Comment by d7i1** [comment]
script up to error:

```
library(aroma.affymetrix)
verbose <- Arguments$getVerbose(-20, timestamp=TRUE)
setOption(aromaSettings, "rules/allowAsciiCdfs", FALSE)
setOption(aromaSettings, "memory/ram", 15.0);
cdf <- AffymetrixCdfFile$byChipType("HuEx-1_0-st-v2", tags = "extendedR3,A20071112,EP")
cs <- AffymetrixCelSet$byName("GSE34184", cdf=cdf)
bc <- GcRmaBackgroundCorrection(cs, tags = "*,extendedR3")
csBC <- process(bc, verbose=verbose)
```


and the traceback after error
```
> traceback()
18: stop(FutureError(future))
17: value.Future(future)
16: value(future)
15: eval(expr, envir, enclos)
14: eval(quote({
        value <- value(future)
        rm(list = future_name, envir = assign.env)
        value
    }), new.env())
13: eval(expr, envir, enclos)
12: eval(expr, p)
11: eval.parent(substitute(eval(quote(expr), envir)))
10: local({
        value <- value(future)
        rm(list = future_name, envir = assign.env)
        value
    })
9: mget(vars[ok], envir = x, inherits = FALSE)
8: as.list.listenv(dataFiles)
7: as.list(dataFiles)
6: process.GcRmaBackgroundCorrection(bc, verbose = verbose)
5: process(bc, verbose = verbose) at 00_ExprNorm.R#19
4: eval(expr, envir, enclos)
3: eval(ei, envir)
2: withVisible(eval(ei, envir))
1: source("Analyse.R")

**Comment by HenrikBengtsson** [comment]
Can you please retry with a single CEL file;
```r
cs <- AffymetrixCelSet$byName("GSE34184", cdf=cdf)
cs <- cs[1]  ## Subset
bc <- GcRmaBackgroundCorrection(cs, tags = "*,extendedR3")
csBC <- process(bc, verbose=verbose)
```

**Comment by HenrikBengtsson** [comment]
Ah... this is an old common mistake (search https://groups.google.com/forum/#!searchin/aroma-affymetrix/); the HuEx-1_0-st-v2 chiptype only has PM's and no MM's so you cannot use the default gcRMA model (`type = "fullmodel"`).  It's very unlikely that it ever worked on that chip type without throwing errors.   Instead use `type = "affinities"`.  You also need to run this step with the original CDF.

BTW, who am I helping out here, i.e. @d7i1 = ...?

**Comment by HenrikBengtsson** [comment]
FYI, aroma.affymetrix 3.1.0 (and aroma.core 3.1.0) are now on CRAN; do an `update.packages()` to get these.

**Comment by d7i1** [comment]
I updated both packages to v3.1.0, and for speed I analysed four arrays. This now works - hope it helps someone.  Thanks very much!

```
library(aroma.affymetrix)
verbose <- Arguments$getVerbose(-20, timestamp=TRUE)
cdf1 <- AffymetrixCdfFile$byChipType("HuEx-1_0-st-v2")
cs <- AffymetrixCelSet$byName("GSE34184", cdf=cdf1)
bc <- GcRmaBackgroundCorrection(cs, type = "affinities")
csBC <- process(bc, verbose=verbose)
cdf2 <- AffymetrixCdfFile$byChipType("HuEx-1_0-st-v2", tags = "coreR3,A20071112,EP")
setCdf(csBC, cdf2)
qn <- QuantileNormalization(csBC, typesToUpdate="pm")
csN <- process(qn, verbose=verbose)

# exon analysis
plmEx <- ExonRmaPlm(csN, mergeGroups=FALSE)
fit(plmEx, verbose=verbose)
cesEx <- getChipEffectSet(plmEx)
exFit <- extractDataFrame(cesEx, units=NULL, addNames=TRUE)

# transcript analysis
plmTr <- ExonRmaPlm(csN, mergeGroups=TRUE)
fit(plmTr, verbose=verbose)
cesTr <- getChipEffectSet(plmTr)
trFit <- extractDataFrame(cesTr, units=NULL, addNames=TRUE)

# alt-splicing analysis
firma <- FirmaModel(plmTr)
fit(firma, verbose=verbose)
fs <- getFirmaScores(firma)
fsFit <- extractDataFrame(fs, units=NULL, addNames=TRUE)
```

**Comment by HenrikBengtsson** [comment]
Yes, that's the way to go.
